name: Codeflash_testing

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest , windows-latest, macOS-latest]
        python-version: ['3.12']
      fail-fast: false
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      COLUMNS: 120
      PYTHONIOENCODING: "utf8"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Update packaging tools
        run: python -m pip install --upgrade pip wheel build

      - name: Install dependencies
        run: python -m pip install codeflash

      - name: run codeflash on the code
        run: codeflash --all --verbose